org: ops360systems
workspaces:
- name: "dio"
  description: "Dev workspace for dhruv dev"
  tags: ["aws", "eks", "dev"]
teams:
- name: "dio-employees-access"
  tags: ["dev"]
  users: ["user1", "user2", "user3"]
permissions:
- team: "dio-employees-access"
  workspace: "dio"
  access: "admin"

